//mutations
export const LOGIN_USER = "LOGIN_USER";
export const RECEIVE_JOBS = "RECEIVE_JOBS";
export const ADD_SELECTED_ORGANIZATIONS = "ADD_SELECTED_ORGANIZATIONS";

//actions
export const FETCH_JOBS = "FETCH_JOBS";

//getters
export const UNIQUE_ORGANIZATIONS = "UNIQUE_ORGANIZATIONS";
export const FILTERED_JOB_BY_ORGANIZATIONS = "FILTERED_JOB_BY_ORGANIZATIONS";
